### PR TITLE
Update SymbolicRegression.jl

### PR DESCRIPTION
**Pull request by MilesCranmer**
See https://github.com/MilesCranmer/SymbolicRegression.jl/pull/84 - should finally be cross-compatible with latest SymbolicUtils.jl

### CODE REVIEW

**Comment by AlCap23** [comment]
I will have a look later this evening. Probably the deps in DataDriven.

**Comment by ChrisRackauckas** [comment]
You probably need to do https://github.com/MilesCranmer/DataDrivenDiffEq.jl/pull/1

**Comment by ChrisRackauckas** [comment]
FYI, I think we should completely eliminate requires and make it a subpackage like how GalacticOptim.jl does it https://github.com/SciML/GalacticOptim.jl

**Comment by AlCap23** [comment]
I'll have to work on fixing some of the issues w.r.t. Symbolics 0.19, which is currently failing. 
Will do that in a different PR and merge it in.

I've taken a quick look at the substructure in GalacticOptim and have to wrap my head around this a little more, but we can take a look at it.

**Comment by AlCap23** [comment]
I'll close this one in favour of #349 where I had to change some additional material and give credit to both of you in the squash if its alright.

**Pull request closed without merging**
