### PR TITLE
MTK 4 Update

### PR DESCRIPTION
**Pull request by AlCap23**
@shashi

Still WIP.

### CODE REVIEW

**Comment by AlCap23** [comment]
I am currently running into World Age issues while converting a Basis into an ODESystem. 

The Basis is now an `AbstractSystem`, so the docs need to be cleaned up.

**Comment by ChrisRackauckas** [comment]
Are you using RuntimeGeneratedFunctions.jl?

**Comment by AlCap23** [comment]
Not directly. I have just adapted using MTK on the current release and used `build_function`

**Comment by AlCap23** [comment]
Using `build_function(args; expression = Val{false})` resolves this locally.

**Comment by AlCap23** [comment]
Alright. I still need to fix one test, which gives out the wrong result right now.

**Comment by AlCap23** [comment]
Should be good to go now after minor updates to the docs ( remove `Operations` etc ).

**Comment by AlCap23** [comment]
I will possibly put a little more works in the docs in other PRs, but right now everything should be properly adapted and is working as expected.

**Review by ChrisRackauckas — APPROVED** [review]

**Comment by AlCap23** [comment]
Alright. I'll merge this and wait for updates, if necessary.

**Pull request merged**
