### PR TITLE
Try to fix CI

### PR DESCRIPTION
**Pull request by YingboMa**

### CODE REVIEW

**Comment by AlCap23** [comment]
Hey @YingboMa !

If it's not urgent, maybe wait for the Draft: Main PR. 

Sorry, I am on mobile right now.

**Comment by YingboMa** [comment]
MTK's CI hasn't been fully passing for months because DataDrivenDiffEq's CI is broken. Should I just remove the downstream tests then?

**Comment by AlCap23** [comment]
Yeah 👍 I'll ping you once Main is ready

**Comment by AlCap23** [comment]
Resolve via #371 and I made a PR in MTK https://github.com/SciML/ModelingToolkit.jl/pull/1953

**Pull request closed without merging**
