### PR TITLE
Update docs

### PR DESCRIPTION
**Pull request by mkg33**
Minor stylistic revisions:
- changed spelling to AmE (note: I refrained from tampering with the file name 'optimisers'/'optimise' because it could break the code; I need to figure out how many parts of the code refer to 'optimisers'/'optimise' to change the name to AmE spelling, but this is a rather pedantic issue)
- punctuation
- typos
- improved the clarity of some sentences

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Thanks!

>changed spelling to AmE (note: I refrained from tampering with the file name 'optimisers'/'optimise' because it could break the code; I need to figure out how many parts of the code refer to 'optimisers'/'optimise' to change the name to AmE spelling, but this is a rather pedantic issue)

Yes, this would be good. I think there's only one spot and it's the highest level module code IIRC

**Comment by mkg33** [comment]
Thanks for the hint! I'm changing it now (along with some new typos I've found). Also, is the word 'likelyhood' in `/src/utils.js` some sort of arcane jargon (that I have no idea about) or is it just a typo? It appears in so many places that I want to be cautious with my revisions :-)

**Comment by ChrisRackauckas** [comment]
>likelyhood

It's supposed to be likelihood, unless @AlCap23 really really wants it to be a new word 😆

**Comment by mkg33** [comment]
Yeah, that's what I thought: a typical copy/paste typo propagation ;-)

**Comment by AlCap23** [comment]
You have found one of my "non native language wrong learning results".  I
tend to have those somehow hardcoded. :)

**Comment by mkg33** [comment]
@AlCap23 Happens to everyone, no worries! There are lots of native speakers (of any language) who make all sorts of possible mistakes ;-)

**Pull request merged**
