### PR TITLE
Upgrade to MTK 4.0

### PR DESCRIPTION
**Pull request by shashi**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Did this not branch off of master?

**Comment by shashi** [comment]
Oh... didn't realize I had my own copy already.

**Comment by AlCap23** [comment]
Hey guys. I've been watching from afar. I hope to squeeze out some dev time next week and would start with converting this. 
I will orient myself at the commits of @shashi and work my way up from there.

**Comment by AlCap23** [comment]
Closed in favor of #168

**Pull request closed without merging**
