### PR TITLE
Parameter estimation

### PR DESCRIPTION
**Pull request by AlCap23**
supersedes #65 .

### CODE REVIEW

**Comment by AlCap23** [comment]
Wait for [GalaticOptim.jl](https://github.com/SciML/GalacticOptim.jl) to go live, which will make this much easier

**Comment by augustinas1** [comment]
Hi @AlCap23, I'm quite interested in constrained SINDy (Algorithm 3 from https://arxiv.org/pdf/1906.10612.pdf) and followed a trail of your PRs here - was wondering what's the status of it? Is there possibly another implementation of constrained SINDy available?

**Comment by AlCap23** [comment]
Hey! Not right now, but once the neverending reminder of the next pr is
done, I'll probably get into this and make at least linear constraints
available.

**Comment by augustinas1** [comment]
Thanks for the update!

**Pull request closed without merging**
